const translations = {
    ru: {
        devNotice: "⚡ Сайт в разработке · актуальная информация на",
        originalSite: "Оригинальный сайт",
        navHome: "Neon Imperium",
        navStarve: "Starve Neon",
        navAlpha: "Alpha 01",
        navGc: "ГК Адвенчур",
        siteTitle: "Neon Imperium",
        mainProjectsTitle: "Главные проекты",
        mainProjectsDesc: "Игры с приоритетом разработки",
        starveDesc: "Выживание в брутальном мире с прокачкой и генетикой.",
        alphaDesc: "Top-down шутер, где вы робот, помогающий солдатам.",
        gcDesc: "Просто приключение ГКТМО.",
        detailsBtn: "Подробнее",
        smallProjectsTitle: "Небольшие проекты",
        smallProjectsDesc: "Игры созданные по рофлу",
        pnsd1Desc: "Первая часть безумной серии.",
        pnsd2Desc: "Продолжение, ещё безумнее.",
        comingSoon: "Скоро",
        developersTitle: "Разработчики",
        developersDesc: "Работаем в свободное время",
        youtubersTitle: "Ютуберы",
        youtubersDesc: "Собираем комьюнити",
        googleSites: "Google Sites",
        trailerTitle: "Трейлер",
        developerTitle: "Разработчик",
        downloadTitle: "Скачать игру",
        descriptionTitle: "Описание",
        videoTitle: "Видео",
        videoDesc: "Подборка контента от сообщества",
        videoHowTo: "Чтобы сюда попасть:",
        videoRule1: "Создай плейлист с настройкой сортировки \"сначала новые\" или \"по популярности\".",
        videoRule2: "Видео в плейлисте должны понравиться разработчику, после чего они могут попасть сюда.",
        updatesTitle: "Обновления",
        polls: "Опросы",
        windowsBtn: "Windows (32/64 бит)",
        androidBtn: "Android (APK)",
        linuxBtn: "Linux",
        downloadNote: "Файлы будут доступны после первого релиза. Следите за обновлениями!",
        starveVersion: "Объединение 0.13.7",
        starveDeveloperRole: "Главный разработчик, геймдизайнер",
        worldTitle: "Игровой мир",
        worldDesc: "БРУТАЛЬНЫЙ ХАРДКОРНЫЙ МИР. Я не буду держать тебя за руку, приятель. Я оставлю небольшой туториал по базовой механике, а дальше ты сам по себе ;}",
        statusTitle: "Статус",
        statusDesc: "Starve Neon находится на ранней стадии разработки, но открыт для кроссплатформенного многопользовательского тестирования.",
        developmentTitle: "Развитие",
        developmentDesc: "Полная система развития от копий и мечей до ГРЕБАНОГО МИНИГАНА, ЧУВАК! Броня для разных биомов, модули и система генетики, подобная RimWorld.",
        alliesTitle: "Союзники",
        alliesDesc: "Создавай союзы с фракциями и другими игроками, участвуй в битвах на арене и приручай животных. Отправляйся кланом на рейд подобно Rust.",
        featuresTitle: "Особенности",
        feature1: "Интернет необязателен.",
        feature2: "Частые крупные обновления.",
        feature3: "Встроенная поддержка модов.",
        feature4: "Прямое общение с разработчиком.",
        feature5: "Многоязычная поддержка и простое добавление пользовательских языков и шрифтов.",
        requirementsTitle: "Системные требования",
        requirementsNote: "Примерные значения основанные на стандартных настройках для этих устройств",
        fps60: "60+ Фпс",
        cpu60: "Процессор: Xeon-E2650 v2 3.00 GHz",
        gpu60: "Видеокарта: GT 730 4GB",
        fps180: "180+ Фпс",
        cpu180: "Процессор: AMD Athlon X4 840 3.10 GHz",
        gpu180: "Видеокарта: GT 1030 2GB",
        fps1000: "1000+ Фпс",
        cpu1000: "Процессор: AMD Ryzen 7 7435HS 4.00 GHz",
        gpu1000: "Видеокарта: RTX 3050 4GB Laptop",
        consumptionTitle: "Потребление",
        consumptionNote: "Примерные значения",
        vram: "Видеопамять",
        vramVal: "512-1024 Мб",
        ram: "Оперативка",
        ramVal: "512-1024 Мб",
        storage: "Память",
        storageVal: "256 Мб",
        os: "Система",
        osVal: "Win 10+ 32 Бит / Андроид 7+",
        video1Title: "Обзор Starve Neon",
        video2Title: "Гайд для новичков",
        video3Title: "Прохождение мультиплеера",
        starveUpdateTitle: "Патч 0.13.7",
        spoilerTutorial: "Туториал",
        tutorialContent: "Цели по всей игре",
        spoilerRewards: "Награды",
        rewardsContent: "Локализация\nУлучшены возможности перевода",
        spoilerQuality: "Удобства",
        qualityContent: "Интерфейс\nУправление",
        spoilerBalance: "Баланс",
        balanceContent: "Награды за уровень\nИзменение прогрессии",
        spoilerBugfix: "Багфикс",
        bugfixContent: "Множество мелких исправлений",
        alphaVersion: "Патч 0.0.5.2",
        alphaDeveloperRole: "Ведущий разработчик",
        alphaDownloadNote: "Версия 0.0.5.2 · Обновление от 21.01.2024",
        alphaStoryTitle: "Сюжет",
        alphaStoryDesc: "Alpha 01 это top-down шутер в котором вы: робот который должен помочь солдатам, но потом всё становится сложнее чем просто помощь...",
        alphaStatusTitle: "Статус",
        alphaStatusDesc: "Игра находится в активной разработке. Текущая версия: 0.0.5.2",
        alphaVideo1Title: "Обзор Alpha 01",
        alphaVideo2Title: "Прохождение",
        alphaUpdateTitle: "Патч 0.0.5.2",
        spoilerGameplay: "Геймплей",
        gameplayContent: "Добавлена 1 точка бандитов на свалке",
        spoilerCraft: "Крафт",
        craftContent: "Метеоритные пули теперь можно скрафтить в лесу",
        spoilerGraphics: "Графика",
        graphicsContent: "Улучшение меню",
        gcVersion: "Обновление 0.1.0",
        gcDeveloperRole: "Главный разработчик",
        gcDownloadNote: "Версия 0.1.0 · Обновление от 01.11.2023",
        gcAboutTitle: "Об игре",
        gcDescription: "Что тут писать? Просто приключение ГКТМО.",
        gcVideo1Title: "Обзор ГК Адвенчур",
        gcUpdateTitle: "Обновление 0.1.0",
        gcUpdateSummary: "Игра вышла",
        gcUpdateContent: "Первый релиз игры."
    },
    en: {
        devNotice: "⚡ Site under development · actual info at",
        originalSite: "Original site",
        navHome: "Neon Imperium",
        navStarve: "Starve Neon",
        navAlpha: "Alpha 01",
        navGc: "GC Adven",
        siteTitle: "Neon Imperium",
        mainProjectsTitle: "Main Projects",
        mainProjectsDesc: "Priority development games",
        starveDesc: "Survival in a brutal world with progression and genetics.",
        alphaDesc: "Top-down shooter where you are a robot helping soldiers.",
        gcDesc: "Just a GC adventure.",
        detailsBtn: "Details",
        smallProjectsTitle: "Small Projects",
        smallProjectsDesc: "Games made for fun",
        pnsd1Desc: "First part of the crazy series.",
        pnsd2Desc: "Sequel, even crazier.",
        comingSoon: "Coming soon",
        developersTitle: "Developers",
        developersDesc: "Working in free time",
        youtubersTitle: "YouTubers",
        youtubersDesc: "Building community",
        googleSites: "Google Sites",
        trailerTitle: "Trailer",
        developerTitle: "Developer",
        downloadTitle: "Download game",
        descriptionTitle: "Description",
        videoTitle: "Video",
        videoDesc: "Community content",
        videoHowTo: "To get here:",
        videoRule1: "Create a playlist with 'newest first' or 'most popular' sorting.",
        videoRule2: "Videos in the playlist must be liked by the developer to be featured.",
        updatesTitle: "Updates",
        polls: "Polls",
        windowsBtn: "Windows (32/64 bit)",
        androidBtn: "Android (APK)",
        linuxBtn: "Linux",
        downloadNote: "Files will be available after the first release. Stay tuned!",
        starveVersion: "Union 0.13.7",
        starveDeveloperRole: "Lead developer, game designer",
        worldTitle: "Game World",
        worldDesc: "BRUTAL HARDCORE WORLD. I won't hold your hand, buddy. I'll leave a short tutorial on the basic mechanics, and then you're on your own ;}",
        statusTitle: "Status",
        statusDesc: "Starve Neon is in early development but open for cross-platform multiplayer tests.",
        developmentTitle: "Development",
        developmentDesc: "Complete development system from spears and swords to F***ING MINIGUN, DUDE! Armor for different biomes, modules and a genetics system similar to RimWorld.",
        alliesTitle: "Allies",
        alliesDesc: "Create alliances with factions and other players, take part in arena battles and tame animals. Go on a raid with your clan like Rust.",
        featuresTitle: "Features",
        feature1: "Internet not required.",
        feature2: "Frequent major updates.",
        feature3: "Built-in mod support.",
        feature4: "Direct communication with the developer.",
        feature5: "Multilingual support and easy addition of custom languages and fonts.",
        requirementsTitle: "System Requirements",
        requirementsNote: "Approximate values based on standard settings for these devices",
        fps60: "60+ FPS",
        cpu60: "CPU: Xeon-E2650 v2 3.00 GHz",
        gpu60: "GPU: GT 730 4GB",
        fps180: "180+ FPS",
        cpu180: "CPU: AMD Athlon X4 840 3.10 GHz",
        gpu180: "GPU: GT 1030 2GB",
        fps1000: "1000+ FPS",
        cpu1000: "CPU: AMD Ryzen 7 7435HS 4.00 GHz",
        gpu1000: "GPU: RTX 3050 4GB Laptop",
        consumptionTitle: "Consumption",
        consumptionNote: "Approximate values",
        vram: "VRAM",
        vramVal: "512-1024 MB",
        ram: "RAM",
        ramVal: "512-1024 MB",
        storage: "Storage",
        storageVal: "256 MB",
        os: "OS",
        osVal: "Win 10+ 32 Bit / Android 7+",
        video1Title: "Starve Neon Review",
        video2Title: "Beginner's Guide",
        video3Title: "Multiplayer Walkthrough",
        starveUpdateTitle: "Patch 0.13.7",
        spoilerTutorial: "Tutorial",
        tutorialContent: "Goals throughout the game",
        spoilerRewards: "Rewards",
        rewardsContent: "Localization\nImproved translation capabilities",
        spoilerQuality: "Quality of Life",
        qualityContent: "Interface\nControls",
        spoilerBalance: "Balance",
        balanceContent: "Level rewards\nProgression changes",
        spoilerBugfix: "Bugfix",
        bugfixContent: "Many minor fixes",
        alphaVersion: "Patch 0.0.5.2",
        alphaDeveloperRole: "Lead developer",
        alphaDownloadNote: "Version 0.0.5.2 · Update 2024-01-21",
        alphaStoryTitle: "Story",
        alphaStoryDesc: "Alpha 01 is a top-down shooter where you are a robot who must help soldiers, but then everything becomes more complicated than just helping...",
        alphaStatusTitle: "Status",
        alphaStatusDesc: "The game is in active development. Current version: 0.0.5.2",
        alphaVideo1Title: "Alpha 01 Review",
        alphaVideo2Title: "Walkthrough",
        alphaUpdateTitle: "Patch 0.0.5.2",
        spoilerGameplay: "Gameplay",
        gameplayContent: "Added 1 bandit point at the dump",
        spoilerCraft: "Crafting",
        craftContent: "Meteorite bullets can now be crafted in the forest",
        spoilerGraphics: "Graphics",
        graphicsContent: "Menu improvement",
        gcVersion: "Update 0.1.0",
        gcDeveloperRole: "Lead developer",
        gcDownloadNote: "Version 0.1.0 · Update 2023-11-01",
        gcAboutTitle: "About",
        gcDescription: "What to write? Just a GC adventure.",
        gcVideo1Title: "GC Adven Review",
        gcUpdateTitle: "Update 0.1.0",
        gcUpdateSummary: "Game released",
        gcUpdateContent: "First release of the game."
    }
};

function setLanguage(lang) {
    document.querySelectorAll('[data-lang]').forEach(element => {
        const key = element.getAttribute('data-lang');
        if (translations[lang] && translations[lang][key]) {
            if (element.tagName === 'INPUT' || element.tagName === 'TEXTAREA') {
                element.placeholder = translations[lang][key];
            } else {
                element.textContent = translations[lang][key];
            }
        }
    });
    document.querySelectorAll('.lang-btn').forEach(btn => {
        btn.classList.toggle('active', btn.dataset.langCode === lang);
    });
    localStorage.setItem('preferredLanguage', lang);
}

document.addEventListener('DOMContentLoaded', () => {
    const savedLang = localStorage.getItem('preferredLanguage') || 'ru';
    setLanguage(savedLang);
    document.querySelectorAll('.lang-btn').forEach(btn => {
        btn.addEventListener('click', () => {
            setLanguage(btn.dataset.langCode);
        });
    });
});